# Generated by Django 3.1.7 on 2021-08-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210815_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='name',
            field=models.CharField(default='User', max_length=300),
        ),
    ]
