# Generated by Django 3.1.7 on 2021-08-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_remove_investor_investments'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='name',
            field=models.CharField(default='Investor', max_length=300),
        ),
        migrations.AddField(
            model_name='investor',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='investors/profile_pics'),
        ),
    ]
